name: Auto-update
# Auto-update only listens to `push` events.
# If pull requests are always based on the same branches, only triggering the workflow when these branches receive new commits will minimize the workflow execution.
on:
  push:
    branches:
      - main

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@6923e6a446fd857f944076793d8a82d53bc1bd89
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}